export const TransactionActionTypes = {
    ADD_IMPORTED_TRANSACTIONS_REQUEST: "ADD_IMPORTED_TRANSACTIONS_REQUEST",
    ADD_IMPORTED_TRANSACTIONS_SUCCESS: "ADD_IMPORTED_TRANSACTIONS_SUCCESS",
    ADD_IMPORTED_TRANSACTIONS_FAILURE: "ADD_IMPORTED_TRANSACTIONS_FAILURE",

    GET_EXPORTED_TRANSACTIONS_REQUEST: "GET_EXPORTED_TRANSACTIONS_REQUEST",
    GET_EXPORTED_TRANSACTIONS_SUCCESS: "GET_EXPORTED_TRANSACTIONS_SUCCESS",
    GET_EXPORTED_TRANSACTIONS_FAILURE: "GET_EXPORTED_TRANSACTIONS_FAILURE",

    GET_TRANSACTIONS_COUNT_REQUEST: "GET_TRANSACTIONS_COUNT_REQUEST",
    GET_TRANSACTIONS_COUNT_SUCCESS: "GET_TRANSACTIONS_COUNT_SUCCESS",
    GET_TRANSACTIONS_COUNT_FAILURE: "GET_TRANSACTIONS_COUNT_FAILURE",

    GET_TRANSACTIONS_PAGE_REQUEST: "GET_TRANSACTIONS_PAGE_REQUEST",
    GET_TRANSACTIONS_PAGE_SUCCESS: "GET_TRANSACTIONS_PAGE_SUCCESS",
    GET_TRANSACTIONS_PAGE_FAILURE: "GET_TRANSACTIONS_PAGE_FAILURE",

    UPDATE_TRANSACTION_STATUS_REQUEST: "UPDATE_TRANSACTION_STATUS_REQUEST",
    UPDATE_TRANSACTION_STATUS_SUCCESS: "UPDATE_TRANSACTION_STATUS_SUCCESS",
    UPDATE_TRANSACTION_STATUS_FAILURE: "UPDATE_TRANSACTION_STATUS_FAILURE",

    DELETE_TRANSACTION_REQUEST: "DELETE_TRANSACTION_REQUEST",
    DELETE_TRANSACTION_SUCCESS: "DELETE_TRANSACTION_SUCCESS",
    DELETE_TRANSACTION_FAILURE: "DELETE_TRANSACTION_FAILURE",
};
